apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeheal-mongodb-pvc
  namespace: kubeheal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeheal-models-pvc
  namespace: kubeheal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeheal-logs-pvc
  namespace: kubeheal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
